### PR TITLE
[Fix #37] Unwrap failure reason within BadResponseError#errorDescription.

### LINKED ISSUE #37: BadResponseError errorDescription with Optional status code
`errorDescription` of `BadResponseError` does not unwrap the `failureReason`. This leads to error messages like `Request failed with Optional("404") return code.`.

```swift
  public var errorDescription: String? {
    return "Request failed with \(String(describing: self.failureReason)) return code."
  }

  public var failureReason: String? {
    if let statusCode = httpResponse?.statusCode {
      return String(describing: statusCode)
    }
    return nil
  }
```

### PR DESCRIPTION
**Pull request by joerghartmann**

### CODE REVIEW

File: Sources/CumulocityCoreLibrary/Supplementary/BadResponseError.swift [hunk 1]
```diff
@@ -15,7 +15,7 @@ public class BadResponseError : LocalizedError {
     public var httpResponse: HTTPURLResponse?
 
     public var errorDescription: String? {
-		return "Request failed with \(String(describing: self.failureReason)) return code."
+		return "Request failed with \(String(describing: self.failureReason ?? 0)) return code."
```
Comment (thomaswinkler) [inline Sources/CumulocityCoreLibrary/Supplementary/BadResponseError.swift:18]: Needs to be a String and not an Int.
